const mongoose = require('mongoose');

const HabitSchema = new mongoose.Schema({
  // Link to the User who owns this habit
  userId: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User', 
    required: true 
  },

  // The UUID generated by Flutter
  localId: { 
    type: String, 
    required: true, 
    unique: true 
  },

  title: { 
    type: String, 
    required: true, 
    trim: true 
  },

  // NEW: Unit (km, liters, etc.)
  unit: { 
    type: String, 
    default: 'count' 
  },
  
  // NEW: Daily Goal (e.g. 5.0)
  target: { 
    type: Number, 
    default: 1 
  },

  // CHANGED: Number instead of String to match Flutter (1 = Daily)
  frequency: { 
    type: Number, 
    default: 1 
  },

  isDeleted: { 
    type: Boolean, 
    default: false 
  },

  // Sync Timestamps
  createdAt: { type: Date, default: Date.now },
  updatedAt: { type: Date, default: Date.now },
  lastSyncedAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Habit', HabitSchema);