const mongoose = require('mongoose');

const HabitLogSchema = new mongoose.Schema({
  userId: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User', 
    required: true 
  },

  // Link to the Habit's localId
  habitLocalId: { 
    type: String, 
    required: true 
  },

  // The UUID of this log generated by Flutter
  localId: { 
    type: String, 
    required: true, 
    unique: true 
  },

  // NEW: The actual number (e.g. 2.5)
  value: { 
    type: Number, 
    required: true 
  },

  completedAt: { 
    type: Date, 
    required: true 
  },

  isDeleted: { 
    type: Boolean, 
    default: false 
  },
  
  syncedAt: { 
    type: Date, 
    default: Date.now 
  }
});

module.exports = mongoose.model('HabitLog', HabitLogSchema);